import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zubstr - Support</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Support
        </h1>

        <p className={styles.description}>
         Please fill the form below and we will get it touch with you shortly!
        </p>

        <div >
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeDI4bB-z2Bp3GfyTBXDnjSKGZp3evXWeETjk6BW-4l-A1LmA/viewform?embedded=true" width="640" height="959" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
        </div>
        <div>
            <p style={{color: "#ccc", fontSize: "12px"}}>
            Zubstr, TADBAN, KALAPATHAR, HYDERABAD, TELANGANA - 500064
Mobile No:	9550476617	Email:	syedzubairahmed001@gmail.com
            </p>
        </div>
      </main>

      
    </div>
  )
}
